Repository Controller-Team/UNDEADER, pull requests merged in 2024-06, with the labels that each got.

#4 Readme 작성 및 이미지 추가
  README.md
  Source/Image/Black.png
Labels: documentation

#9 [Docs] PR 템플릿 수정
  .github/pull_request_template.md
Labels: documentation, fix

#8 [Feat] HP Bar, Stamina, Remain Time HUD 구현
  Content/Blueprints/HUD/WBP_HUD.uasset
Labels: feature

#12 [Feat] 피격 시 매테리얼 오버레이 설정
  Content/Overlay/BP_Overlay.uasset
  Content/Overlay/M_Overlay.uasset
Labels: feature

#14 [Feat] 플레이어 HUD 기능 구현 및 연동 (+기타 버그 수정)
  Content/Blueprints/BP_EnemySpawner.uasset
  Content/Blueprints/BP_SpawnPoint.uasset
  Content/Blueprints/BP_ThirdPersonGameMode.uasset
  Content/Blueprints/Components/HealthSystem.uasset
  Content/Blueprints/Components/StaminaSystem.uasset
  Content/Blueprints/Enemys/AN_attack.uasset
  Content/Blueprints/Enemys/BP_EnemyBase.uasset
  Content/Blueprints/HealthSystem.uasset
  Content/Blueprints/Level/BP_EnemySpawner.uasset
  Content/Blueprints/Level/BP_EscapeArea.uasset
  Content/Blueprints/Level/BP_SpawnPoint.uasset
  Content/Blueprints/PlayerCharacter/BP_PlayerCharacter.uasset
  Content/Sample.umap
  Content/ThirdPerson/UI/HealthSystem.uasset
Labels: feature

#16 [Fix] HP Bar Clamp 작업 및 탈출가능 함수 추가
  Content/Blueprints/HUD/WBP_HUD.uasset
Labels: fix

#18 [Feat] 게임 타이틀 HUD 완성
  Content/Blueprints/HUD/WBP_Title.uasset
  Content/Images/GameLogo.uasset
Labels: feature
